### ISSUE TITLE
Type error: `direction` on `Stack` component

### ISSUE THREAD

**Issue by jrinehart-apex** [julians-apex/poke-app#1]
I tried to push a fix, but don't have access to the repo, probably cuz it's your personal fork?

There is a type error when interview candidates open the app for the first time:

```
Expression produces a union type that is too complex to represent.ts(2590)
```

It's a little jarring for them to be presented with a whole editor full of red squiggles right off the bat. :smile:

The error is caused by [the `direction` prop on a `Stack` component](https://github.com/julians-apex/poke-app/blob/main/src/App.tsx#L19).  If you change the `direction="row"` prop to `flexDir="row"` it circumnavigates the issue while still resulting in the same styling.

```tsx
<Stack direction='row' spacing={0}>
// change to...
<Stack flexDir='row' spacing={0}>
```

**Comment by julians-apex** [comment]
Fixed. Thanks for the solution
